### ISSUE TITLE
请问,如何部署到 vps 上面啊

### ISSUE THREAD

**Issue by Alife** [vjudge1/mirrorrr-plus#11]

**Comment by vjudge1** [comment]
说实话我也不知道如何部署，甚至不知道它还能不能跑了。如果只想让它跑起来，不考虑其他事情的话，大概可以用[SDK](https://cloud.google.com/appengine/downloads)，只不过app.yaml可能得改……反正肯定免不了折腾了。

**Comment by Alife** [comment]
哦那我去别的地方问问看，Google了也没结果都是部署到 gae 上的。
还是谢谢啊。
